export { default as DashboardView } from './DashboardView/DashboardView'
export { default as LandingView } from './LandingView/LandingView'
export { default as LoginView } from './LoginView/LoginView'
export { default as RegisterView } from './RegisterView/RegisterView'
export { default as NotFoundView } from './NotFoundView/NotFoundView'
export { default as PanelView } from './PanelView/PanelView'